baseurl = "https://mikailgultekin.com/"
languageCode = "en-us"
title = "Mikail Gültekin"
theme = "cactus"

pygmentscodefencesguesssyntax = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
pygmentsstyle = "vs"

rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed to Mikail Gültekin" # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
googleAnalytics = "UA-134220309-1" # Enter your tracking code to enable Google Analytics
# disqusShortname = "spf13" # Disable comments by leaving disqusShortname empty

[params]
name = "Mikail Gültekin"
description = "My Personal Blog"
bio = "Programmer & Blogger"
twitter = "gultekinmikail" # Enter optionally your twitter account
enableRSS = true
subscribe = "RSS"

# Integrate Javascript files or stylesheets by adding the url to the external assets or by
# linking local files with their path relative to the static folder, e.g. "css/styles.css"
customCSS = []
customJS  = []

# The variables below are optionally too and can be used to
# translate or customize each string of the theme.

# Navigation links
home = ""

# Pagination links
olderPosts = ""
newerPosts = ""
readMore = ""
copyright = ""

# Sharing options and author information in posts
aboutAuthor = "Programmer & Blogger"
tweet = ""
share = ""

# 404 page
title404 = ""
subtitle404 = ""

iconFont = "mono-social" # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
socialIconStyle = "rounded" # The social icons can be styled differently if you use mono as font - circle, rounded, or empty

[social] # Add additional social link entries underneath
twitter  = "https://twitter.com/gultekinmikail/"
github   = "https://github.com/mikail-gultekin/"
linkedin = "https://www.linkedin.com/in/mikailgultekin/"